language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: vowh8M5/0L9jFfemMAIGbJH6VsdwrzN5kFLjfhg/U0b5Y8cKB5IP8JzhIYwurnL5vBrrmV0jWDQKbLczeNXd/cDCjRJ6EfY+JImvTF62x/14zsfhGXbx0Pag4Y5Pq+Vyjb3XYDvTMkIKIQWBKUQcBl55/LGXk5LJz+pO3+fFTfbwGKVze7DtWdPRiOOBxqHV9MhhBZemixpH4sZ6htrwNBdhbZu3UjPOdwEb7WG7Oc/UU+Zxr/osolKGqgJ/NDEj+TQgPUvDJXFMRBVTSezas3CL3GbzZYyGxFR0zzPdfQ9I0mZhpPIVWACrE+jVczGfKtijr3anfFP4DNuBiVdNIMPl85g2r8+q7VitTqIkV4300Ko7VtZLffo6ttUhXMue4y9VA+7y+ee2Sd3dF/7/luVP+7MdepJ64Af6XU57mYqn75iXO4IuUdG5Emfwdws6ELFevWc49K2J/sy9JMaOgupWF8zo57zvzaXxKkVGSztMFEtsJEXEi4MAFQuahBsvSxlMZADEawfeVbw79cHt6DJqrx4qQAkzlfRgtZAmKap5z9Xs04U5Tea0u13811a40kmKuHfWJqnbTbRM4d6VUIIcGeBBF37Jxxp9pvdnSWZz0opwoUeOsMbMY70lkPx3V9wZG+l/XSFMWEYmuiX4vmWNAmScyDfQYUKU6qNtIFY=
  app: evening-woodland-75028
  on:
    repo: Robp773/work-wherever-api
